### ISSUE TITLE
[BUG] Proxmox PVE is detected as vanilla Debian

### ISSUE THREAD

**Issue by cedricroijakkers** [fastfetch-cli/fastfetch#889] opened 2024-05-06 07:08 UTC
# General description of bug:

I have a server running [Proxmox PVE](https://www.proxmox.com/en/proxmox-virtual-environment/overview) installed from the Proxmox ISO (so not first installed Debian, and then installed the Proxmox packages on top of it).

Neofetch detects it as Proxmox, but Fastfetch detects it as vanilly debian:

```shell
root@pve:~# neofetch 
         .://:`              `://:.            root@pve 
       `hMMMMMMd/          /dMMMMMMh`          -------- 
        `sMMMMMMMd:      :mMMMMMMMs`           OS: Proxmox VE 8.2.2 x86_64 
`-/+oo+/:`.yMMMMMMMh-  -hMMMMMMMy.`:/+oo+/-`   Kernel: 6.8.4-2-pve 
`:oooooooo/`-hMMMMMMMyyMMMMMMMh-`/oooooooo:`   Uptime: 9 days, 19 hours, 51 mins 
  `/oooooooo:`:mMMMMMMMMMMMMm:`:oooooooo/`     Packages: 790 (dpkg) 
    ./ooooooo+- +NMMMMMMMMN+ -+ooooooo/.       Shell: bash 5.2.15 
      .+ooooooo+-`oNMMMMNo`-+ooooooo+.         Terminal: /dev/pts/0 
        -+ooooooo/.`sMMs`./ooooooo+-           CPU: 13th Gen Intel CoreT i5-1340P (16) @ 4.600GHz 
          :oooooooo/`..`/oooooooo:             GPU: Intel Raptor Lake-P [Iris Xe Graphics] 
          :oooooooo/`..`/oooooooo:             Memory: 16165MiB / 64055MiB 
        -+ooooooo/.`sMMs`./ooooooo+-
      .+ooooooo+-`oNMMMMNo`-+ooooooo+.                                 
    ./ooooooo+- +NMMMMMMMMN+ -+ooooooo/.                               
  `/oooooooo:`:mMMMMMMMMMMMMm:`:oooooooo/`
`:oooooooo/`-hMMMMMMMyyMMMMMMMh-`/oooooooo:`
`-/+oo+/:`.yMMMMMMMh-  -hMMMMMMMy.`:/+oo+/-`
        `sMMMMMMMm:      :dMMMMMMMs`
       `hMMMMMMd/          /dMMMMMMh`
         `://:`              `://:`

root@pve:~# fastfetch 
       _,met$$$$$gg.           root@pve
    ,g$$$$$$$$$$$$$$$P.        --------
  ,g$$P"         """Y$$.".     OS: Debian GNU/Linux bookworm 12.5 x86_64
 ,$$P'               `$$$.     Kernel: 6.8.4-2-pve
',$$P       ,ggs.     `$$b:    Uptime: 9 days, 19 hours, 51 mins
`d$$'     ,$P"'   .    $$$     Packages: 790 (dpkg)
 $$P      d$'     ,    $$$P    Shell: bash 5.2.15
 $$:      $.   -    ,d$$'      Terminal: /dev/pts/0
 $$;      Y$b._   _,d$P'       CPU: 13th Gen Intel(R) CoreT i5-1340P (16) @ 4.60 GHz
 Y$$.    `.`"Y$$$$P"'          GPU: Intel Iris Xe Graphics @ 1.45 GHz [Integrated]
 `$$b      "-.__               Memory: 16.28 GiB / 62.55 GiB (26%)
  `Y$$                         Swap: Disabled
   `Y$$.                       Disk (/): 2.12 GiB / 3.47 TiB (0%) - zfs
     `$$b.                     Disk (/rpool): 128.00 KiB / 3.47 TiB (0%) - zfs
       `Y$$b.                  Local IP (vmbr0): 192.168.137.2/24 *
          `"Y$b._              Locale: en_US.UTF-8
             `"""
                               ████████████████████████
                               ████████████████████████
```

* Fastfetch version used: 2.11.3 (x86_64)
* Did it work in an older version: N/A
* Where did you get the binary: Github Release

Screenshot:
![image](https://github.com/fastfetch-cli/fastfetch/assets/15158042/9d902845-d57b-48c5-ba94-f741ff46ec94)

Output of `fastfetch -c ci.jsonc --format json`:
```
[
  {
    "type": "Title",
    "result": {
      "userName": "root",
      "hostName": "pve",
      "homeDir": "/root/",
      "exePath": "/usr/bin/fastfetch",
      "userShell": "/bin/bash",
      "pageSize": 4096
    },
    "stat": 0
  },
  {
    "type": "Separator",
    "error": "Unsupported for JSON format",
    "stat": 0
  },
  {
    "type": "OS",
    "result": {
      "buildID": "",
      "codename": "bookworm",
      "id": "debian",
      "idLike": "",
      "name": "Debian GNU/Linux",
      "prettyName": "Debian GNU/Linux 12 (bookworm)",
      "variant": "",
      "variantID": "",
      "version": "12.5",
      "versionID": "12.5"
    },
    "stat": 0
  },
  {
    "type": "Host",
    "error": "neither product_family nor product_name is set by O.E.M.",
    "stat": 0
  },
  {
    "type": "Bios",
    "result": {
      "date": "09/16/2023",
      "release": "5.27",
      "vendor": "American Megatrends International, LLC.",
      "version": "5.27",
      "type": "UEFI"
    },
    "stat": 0
  },
  {
    "type": "Board",
    "error": "board_name is not set.",
    "stat": 0
  },
  {
    "type": "Chassis",
    "result": {
      "type": "Desktop",
      "vendor": "",
      "version": "",
      "serial": ""
    },
    "stat": 0
  },
  {
    "type": "Kernel",
    "result": {
      "architecture": "x86_64",
      "name": "Linux",
      "release": "6.8.4-2-pve",
      "version": "#1 SMP PREEMPT_DYNAMIC PMX 6.8.4-2 (2024-04-10T17:36Z)",
      "displayVersion": ""
    },
    "stat": 0
  },
  {
    "type": "Uptime",
    "result": {
      "uptime": 849361940,
      "bootTime": "2024-05-16T05:02:40.831+0200"
    },
    "stat": 0
  },
  {
    "type": "Processes",
    "result": 386,
    "stat": 0
  },
  {
    "type": "Packages",
    "result": {
      "all": 790,
      "apk": 0,
      "brew": 0,
      "brewCask": 0,
      "choco": 0,
      "dpkg": 790,
      "emerge": 0,
      "eopkg": 0,
      "flatpakSystem": 0,
      "flatpakUser": 0,
      "nixDefault": 0,
      "nixSystem": 0,
      "nixUser": 0,
      "pacman": 0,
      "paludis": 0,
      "pkg": 0,
      "pkgtool": 0,
      "macports": 0,
      "rpm": 0,
      "scoop": 0,
      "snap": 0,
      "winget": 0,
      "xbps": 0,
      "opkg": 0,
      "am": 0,
      "sorcery": 0,
      "pacmanBranch": ""
    },
    "stat": 1
  },
  {
    "type": "Shell",
    "result": {
      "exe": "bash",
      "exeName": "bash",
      "exePath": "/usr/bin/bash",
      "pid": 2873295,
      "ppid": 2873272,
      "processName": "bash",
      "prettyName": "bash",
      "version": "5.2.15",
      "tty": 0
    },
    "stat": 1
  },
  {
    "type": "Display",
    "error": "Couldn't detect display",
    "stat": 2
  },
  {
    "type": "Brightness",
    "result": [],
    "stat": 0
  },
  {
    "type": "Monitor",
    "error": "No monitors found",
    "stat": 0
  },
  {
    "type": "LM",
    "result": {
      "service": "sshd",
      "type": "TTY",
      "version": "9.2p1 Debian-2+deb12u2"
    },
    "stat": 3
  },
  {
    "type": "DE",
    "error": "No DE found",
    "stat": 0
  },
  {
    "type": "WM",
    "error": "No WM found",
    "stat": 0
  },
  {
    "type": "WMTheme",
    "error": "WM Theme needs successful WM detection",
    "stat": 0
  },
  {
    "type": "Theme",
    "error": "No themes found",
    "stat": 0
  },
  {
    "type": "Icons",
    "error": "No icons could be found",
    "stat": 0
  },
  {
    "type": "Font",
    "error": "No fonts found",
    "stat": 0
  },
  {
    "type": "Cursor",
    "error": "Couldn't find cursor",
    "stat": 0
  },
  {
    "type": "Wallpaper",
    "error": "Failed to detect the current wallpaper path",
    "stat": 0
  },
  {
    "type": "Terminal",
    "result": {
      "processName": "/dev/pts/0",
      "exe": "/dev/pts/0",
      "exeName": "0",
      "exePath": "",
      "pid": 0,
      "ppid": 0,
      "prettyName": "/dev/pts/0",
      "version": "",
      "tty": "/dev/pts/0"
    },
    "stat": 0
  },
  {
    "type": "TerminalFont",
    "error": "Terminal font detection is not supported on PTS",
    "stat": 0
  },
  {
    "type": "TerminalSize",
    "result": {
      "columns": 227,
      "rows": 55,
      "width": 0,
      "height": 0
    },
    "stat": 0
  },
  {
    "type": "TerminalTheme",
    "error": "Failed to detect terminal theme",
    "stat": 0
  },
  {
    "type": "CPU",
    "result": {
      "cpu": "13th Gen Intel(R) CoreT i5-1340P",
      "vendor": "GenuineIntel",
      "cores": {
        "physical": 12,
        "logical": 16,
        "online": 16
      },
      "frequency": {
        "base": 1.9,
        "max": 4.6,
        "min": 0.4
      },
      "temperature": null
    },
    "stat": 0
  },
  {
    "type": "CPUUsage",
    "result": [
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      9.090909090909092,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0
    ],
    "stat": 201
  },
  {
    "type": "GPU",
    "result": [
      {
        "coreCount": null,
        "memory": {
          "dedicated": {
            "total": null,
            "used": null
          },
          "shared": {
            "total": null,
            "used": null
          }
        },
        "driver": "i915",
        "name": "Iris Xe Graphics",
        "temperature": null,
        "type": "Integrated",
        "vendor": "Intel",
        "platformApi": "",
        "frequency": 1.45
      }
    ],
    "stat": 1
  },
  {
    "type": "Memory",
    "result": {
      "total": 67167444992,
      "used": 17336172544
    },
    "stat": 0
  },
  {
    "type": "Swap",
    "result": {
      "total": 0,
      "used": 0
    },
    "stat": 0
  },
  {
    "type": "Disk",
    "result": [
      {
        "bytes": {
          "available": 3816429977600,
          "free": 3816429977600,
          "total": 3818704994304,
          "used": 2275016704
        },
        "files": {
          "total": 3159055186,
          "used": 57602
        },
        "filesystem": "zfs",
        "mountpoint": "/",
        "mountFrom": "rpool/ROOT/pve-1",
        "name": "",
        "volumeType": [
          "Regular"
        ],
        "createTime": "2023-12-22T13:17:01.814+0100"
      },
      {
        "bytes": {
          "available": 3816429977600,
          "free": 3816429977600,
          "total": 3816430108672,
          "used": 131072
        },
        "files": {
          "total": 3158997592,
          "used": 8
        },
        "filesystem": "zfs",
        "mountpoint": "/rpool",
        "mountFrom": "rpool",
        "name": "",
        "volumeType": [
          "Regular"
        ],
        "createTime": "2023-12-22T13:17:01.786+0100"
      },
      {
        "bytes": {
          "available": 3816429977600,
          "free": 3816429977600,
          "total": 3816430108672,
          "used": 131072
        },
        "files": {
          "total": 3158997591,
          "used": 7
        },
        "filesystem": "zfs",
        "mountpoint": "/rpool/ROOT",
        "mountFrom": "rpool/ROOT",
        "name": "",
        "volumeType": [
          "Subvolume"
        ],
        "createTime": "2023-12-22T13:17:01.806+0100"
      },
      {
        "bytes": {
          "available": 3816429977600,
          "free": 3816429977600,
          "total": 3816430108672,
          "used": 131072
        },
        "files": {
          "total": 3158997590,
          "used": 6
        },
        "filesystem": "zfs",
        "mountpoint": "/rpool/data",
        "mountFrom": "rpool/data",
        "name": "",
        "volumeType": [
          "Subvolume"
        ],
        "createTime": "2023-12-22T13:17:01.826+0100"
      },
      {
        "bytes": {
          "available": 3816429977600,
          "free": 3816429977600,
          "total": 3823179137024,
          "used": 6749159424
        },
        "files": {
          "total": 3158997601,
          "used": 17
        },
        "filesystem": "zfs",
        "mountpoint": "/var/lib/vz",
        "mountFrom": "rpool/var-lib-vz",
        "name": "",
        "volumeType": [
          "Subvolume"
        ],
        "createTime": "2023-12-22T13:17:01.838+0100"
      }
    ],
    "stat": 0
  },
  {
    "type": "Battery",
    "result": [],
    "stat": 0
  },
  {
    "type": "PowerAdapter",
    "result": [],
    "stat": 0
  },
  {
    "type": "Player",
    "error": "Failed to connect to DBus",
    "stat": 0
  },
  {
    "type": "Media",
    "error": "Failed to connect to DBus",
    "stat": 0
  },
  {
    "type": "PublicIp",
    "result": {
      "ip": "95.182.146.83",
      "location": "Visé, BE"
    },
    "stat": 303
  },
  {
    "type": "LocalIp",
    "result": [
      {
        "defaultRoute": true,
        "ipv4": "192.168.137.2/24",
        "ipv6": "",
        "mac": "",
        "name": "vmbr0"
      }
    ],
    "stat": 1
  },
  {
    "type": "Wifi",
    "error": "linux/wireless.h not found during compilation",
    "stat": 0
  },
  {
    "type": "DateTime",
    "result": "2024-05-06T09:06:39.404+0200",
    "stat": 0
  },
  {
    "type": "Locale",
    "result": "en_US.UTF-8",
    "stat": 0
  },
  {
    "type": "Vulkan",
    "error": "ffvkCreateInstance() failed",
    "stat": 2
  },
  {
    "type": "OpenGL",
    "error": "dlopen glx failed",
    "stat": 0
  },
  {
    "type": "OpenCL",
    "error": "dlopen libOpenCL.so failed",
    "stat": 0
  },
  {
    "type": "Users",
    "result": [
      {
        "name": "root",
        "hostName": "192.168.137.100",
        "sessionName": "pts/0",
        "clientIp": "192.168.137.100",
        "loginTime": "2024-05-06T08:59:22.792+0200"
      }
    ],
    "stat": 0
  },
  {
    "type": "Bluetooth",
    "error": "Failed to call GetManagedObjects",
    "stat": 1
  },
  {
    "type": "Sound",
    "error": "Failed to connect to pulseaudio context",
    "stat": 4
  },
  {
    "type": "Camera",
    "error": "Fastfetch was compiled without <linux/videodev2.h>",
    "stat": 0
  },
  {
    "type": "Gamepad",
    "result": [],
    "stat": 0
  },
  {
    "type": "Weather",
    "result": "+13°C - Partly cloudy (Vise, Belgium)",
    "stat": 0
  },
  {
    "type": "NetIO",
    "result": [
      {
        "name": "vmbr0",
        "defaultRoute": true,
        "txBytes": 1058,
        "rxBytes": 1496,
        "txPackets": 14,
        "rxPackets": 12,
        "rxErrors": 0,
        "txErrors": 0,
        "rxDrops": 1,
        "txDrops": 0
      }
    ],
    "stat": 480
  },
  {
    "type": "DiskIO",
    "result": [
      {
        "name": "WD Blue SN580 2TB",
        "devPath": "/dev/nvme0n1",
        "bytesRead": 561152,
        "bytesWritten": 8192,
        "readCount": 9,
        "writeCount": 2
      },
      {
        "name": "WD Blue SN580 2TB",
        "devPath": "/dev/nvme1n1",
        "bytesRead": 172032,
        "bytesWritten": 40960,
        "readCount": 3,
        "writeCount": 2
      }
    ],
    "stat": 0
  },
  {
    "type": "PhysicalDisk",
    "result": [
      {
        "name": "WD Blue SN580 2TB",
        "devPath": "/dev/nvme0n1",
        "interconnect": "NVMe",
        "kind": "SSD",
        "size": 2000398934016,
        "serial": "2343LV404912",
        "removable": false,
        "readOnly": false,
        "revision": "281010WD",
        "temperature": null
      },
      {
        "name": "WD Blue SN580 2TB",
        "devPath": "/dev/nvme1n1",
        "interconnect": "NVMe",
        "kind": "SSD",
        "size": 2000398934016,
        "serial": "2343LV406013",
        "removable": false,
        "readOnly": false,
        "revision": "281010WD",
        "temperature": null
      }
    ],
    "stat": 0
  },
  {
    "type": "Version",
    "result": {
      "projectName": "fastfetch",
      "architecture": "x86_64",
      "version": "2.11.3",
      "versionTweak": "",
      "cmakeBuiltType": "RelWithDebInfo",
      "compileTime": "May  4 2024, 12:49:45",
      "compiler": "gcc 9.4.0",
      "debugMode": false,
      "libc": "glibc 2.31"
    },
    "stat": 0
  },
  {
    "type": "Break",
    "error": "Unsupported for JSON format",
    "stat": 0
  },
  {
    "type": "Colors",
    "error": "Unsupported for JSON format",
    "stat": 0
  }
]

```

Output of `fastfetch --list-features`:
```
threads
vulkan
wayland
xcb-randr
xcb
xrandr
x11
drm
gio
dconf
dbus
imagemagick7
imagemagick6
chafa
zlib
xfconf
sqlite3
egl
glx
osmesa
opencl
libpulse
libnm
libddcutil
Directx Headers
Proprietary GPU driver API
```

* The bug is reproduceable with fresh / clean shell configuration (i.e. `fastfetch` is the single line of `.zshrc` or `~/.config/fish/config.fish`): yes
* Does `sleep 1` before running `fastfetch` work?  No

**Comment by CarterLi** [comment] 2024-05-06 07:35
Duplicate of https://github.com/fastfetch-cli/fastfetch/issues/507

Does this distro have `/etc/lsb-release`?

**Closed** 2024-05-06 10:44 UTC
Labels: bug
