### ISSUE TITLE
[BUG] Publicip module works ~ 20% of the time in LXC-containers

### ISSUE THREAD

**Issue by borestad** [fastfetch-cli/fastfetch#763] opened 2024-03-18 15:35 UTC
# General description of bug:

* What happened:  
`Public IP: Failed to receive the server response             25ms`
* What should happen:
Public ip shold be shown consistently
* Did it work in an older version: not sure
* 
* Where did you get the binary: Github Release
* Does this issue still occurs in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)?

# Often helpful information:
fastfetch 2.8.9 (x86_64)
(Tested in almalinux, debian, alpine, same issue)

Screenshot:
9 out of 10 tries
<img width="918" alt="image" src="https://github.com/fastfetch-cli/fastfetch/assets/286455/81b5926f-dab9-4dcf-bb1c-0fd4c1938299">

Finally, after 10 tries
<img width="892" alt="image" src="https://github.com/fastfetch-cli/fastfetch/assets/286455/6b029a00-fcfd-4c7b-9f05-1db078ca4881">

...and then same issue again.
<img width="906" alt="image" src="https://github.com/fastfetch-cli/fastfetch/assets/286455/e821fd31-a837-45ec-8da7-ce93618fa7eb">

* The content of the configuration file you use (if any):
No config file used

```
Output of `fastfetch --list-features`:
```

```
❯ fastfetch --list-features
threads
vulkan
wayland
xcb-randr
xcb
xrandr
x11
drm
gio
dconf
dbus
imagemagick7
imagemagick6
zlib
xfconf
sqlite3
rpm
egl
glx
osmesa
opencl
libpulse
libnm
libddcutil
videodev2
Directx Headers
Proprietary GPU driver API
```

* Does `sleep 1` before running `fastfetch` work? 
No

I've tried with multiple providers
* icanhazip.com
* ipv4.icanhazip.com 
* v4.ident.me

tried with both https & http and without (read the sourcecode here https://github.com/fastfetch-cli/fastfetch/blob/7c5eb021ee81e42a77b1eae73c9691e23cdd12ab/src/detection/publicip/publicip.c#L20)

I can see in my firewall that the requests are outgoing/incoming, so there's nothing wrong with the network. Tried on multiple machines. After some more debugging, most of the issue seems to be from LXC-containers though.

**Comment by CarterLi** [comment] 2024-03-18 15:49
Did a quick test. I didn't reproduce the issue but I did find `Public IP` lacks a line ending trimming. I will test it more tomorrow.

> tried with both https & http and without (read the sourcecode here

Yeah to make it simple, https requests are not supported.

An easy workaround:

```
fastfetch -s title:localip:command --command-text 'curl http://ipv4.icanhazip.com' --command-key 'Public IP'
```

**Comment by CarterLi** [comment] 2024-03-18 16:12
Just notice that you are running it in a container. Is this issue reproduceable in your physical machine?

**Comment by borestad** [comment] 2024-03-18 17:57
Awesome!

`time fastfetch -s title:localip:command --command-text 'curl http://ipv4.icanhazip.com' --command-key 'Public IP'` seems to work  every single time. 50 of 50 tries now.

with http ~ `50ms`
with https ~ `94ms`

curl 
~ 50ms `time /usr/bin/curl -sL http://ipv4.icanhazip.com `
~ 95ms `time /usr/bin/curl -sL https://ipv4.icanhazip.com `

No, apparently I can only reproduce this in a LXC container, which makes it really really weird. Can't really figure out what could be the difference between lxc/kvm/host ....

**Comment by CarterLi** [comment] 2024-03-19 10:40
Since this issue doesn't occur in host, I'd rather call it a container bug instead of a fastfetch bug, because a container should behave like physical machines.

Closing. If you are able to debug this issue inside the container, any contribution will be appreciated.

**Closed by CarterLi** 2024-03-19 10:40 UTC
Labels: bug, has workaround

**Comment by CarterLi** [comment] 2024-03-20 08:21
With my recent commit 85da30ccf532c15dd019d9d59eb1890e2953c17e fastfetch will print more useful error messages. Can you try the dev build in LXC-containers with `fastfetch --pipe -s publicip 
--publicip-url whatever --show-errors --thread false`?

**Comment by borestad** [comment] 2024-03-20 15:17
Hi!
Yes .... tried and got:
`Public IP: Empty server response received`

**Comment by CarterLi** [comment] 2024-03-21 03:13
I guess that it was because `recv` returned less data than expected for some reason.

Made a fix, please have a test.

**Comment by borestad** [comment] 2024-03-21 04:08
Still same error .....

`./fastfetch --pipe -s publicip --publicip-url http://icanhazip.com --show-errors --thread false`
This is beyond weird. I actually did a `tcpflow -p -c port 80` test and captured the data.

* To the left is the response with `Public IP: Empty server response received`
* To the right is the response with my public ip.

....i masked the ip somewhat...but still. The responses are the same. What !? 🤔
https://www.diffchecker.com/eIAnCFai/

<img width="1516" alt="image" src="https://github.com/fastfetch-cli/fastfetch/assets/286455/d4401ea7-53f0-48ab-8890-10d0d7916b21">

**Comment by CarterLi** [comment] 2024-03-21 04:13
What does strace print?
