### ISSUE TITLE
[BUG] Can't detect flatpak package on system

### ISSUE THREAD

**Issue by wychlw** [fastfetch-cli/fastfetch#1093] opened 2024-07-14 10:36 UTC
Be sure to read the [FAQ](https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#faq) before submitting a new issue.

# General description of bug:

* What happened: Don't output flatpak package count in Packages
* What should happen: Should display flatpak count on the system
* Fastfetch version used: fastfetch 2.18.1-6 (x86_64)
* Did it work in an older version: unsure
* Where did you get the binary: Arch Linux Pacman and built from dev branch HEAD
* Does this issue still occur in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)? Yes

# Often helpful information:

You can see from the ci.jsonc below, where flatpak User and System are both 0:
```json
  {
    "type": "Packages",
    "result": {
      "flatpakSystem": 0,
      "flatpakUser": 0,
    }
}
```

`flatpak list` gives 6 packages:
```log
❯ flatpak list
名称                                       应用程序 ID                              版本       分支            安装
Mesa                                       org.freedesktop.Platform.GL.default      23.0.2     22.08           system
Mesa (Extra)                               org.freedesktop.Platform.GL.default      23.0.2     22.08-extra     system
freedesktop 平台 翻译                      org.freedesktop.Platform.Locale                     22.08           system
Intel                                      org.freedesktop.Platform.VAAPI.Intel                22.08           system
openh264                                   org.freedesktop.Platform.openh264        2.1.0      2.2.0           system
GNOME Application Platform version 43      org.gnome.Platform                                  43              system
```

So does `ls -l /var/lib/flatpak/{app,runtime}`:
```log
❯ ls -l /var/lib/flatpak/{app,runtime}
/var/lib/flatpak/app:
总计 0

/var/lib/flatpak/runtime:
总计 24
drwxr-xr-x 3 root root 4096 2023年Apr 4日 org.freedesktop.Platform.GL.default
drwxr-xr-x 3 root root 4096 2023年Apr 5日 org.freedesktop.Platform.Locale
drwxr-xr-x 3 root root 4096 2023年Apr 4日 org.freedesktop.Platform.openh264
drwxr-xr-x 3 root root 4096 2023年Apr 4日 org.freedesktop.Platform.VAAPI.Intel
drwxr-xr-x 3 root root 4096 2023年Apr 4日 org.gnome.Platform
drwxr-xr-x 3 root root 4096 2023年Apr 4日 org.gnome.Platform.Locale
```

So should have at least 6 system flatpak package?

Output of `fastfetch -c ci.jsonc --format json`:
[github gist](https://gist.github.com/wychlw/412cecad6423e3301e2ca24b3bdfd070)

Output of `fastfetch --list-features`:
```
threads
vulkan
wayland
xcb-randr
xcb
xrandr
x11
drm
gio
dconf
dbus
imagemagick7
chafa
zlib
xfconf
egl
glx
osmesa
opencl
libpulse
libnm
libddcutil
Directx Headers
System yyjson
linux/videodev2
linux/wireless
```

**Comment by CarterLi** [comment] 2024-07-14 11:37
We now detects only `apps`, not `runtimes`

**Comment by CarterLi** [comment] 2024-07-14 11:38
It seems meaningless to install only runtimes. Why did you do that?

**Comment by CarterLi** [comment] 2024-07-15 02:22
Closing as not a bug

**Closed by CarterLi** 2024-07-15 02:22 UTC
Labels: bug
